########################################
#
# Library of Alexandria hugo config
# Doc is see http://gohugo.io/overview/configuration/
#
########################################

builddrafts = true
baseurl = "https://libraryofalexandria.io/"
canonifyurls = true
editor = "nvim"
title = "Library of Alexandria"
theme = "nofancy"

[author]
  name = "zchee - Koichi Shiraishi"
  github = "zchee"
  # linkedin = "YOUR LINKEDIN ID"
  # facebook = "YOUR FB ID"
  # gaID = "YOUR Google Analytics Tracking ID"
  twitter = "_zchee_"

[permalinks]
  post = "/:filename/"
  # post = "/:year/:month/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Library of Alexandria"
  author = "zchee <Koichi Shiraishi>"
  highlight="dark"
