########################################
#
# Library of Alexandria hugo config
# Doc is see http://gohugo.io/overview/configuration/
#
########################################

builddrafts = true
baseurl = "http://libraryofalexandria.io/"
canonifyurls = true
editor = "nvim"
title = "Library of Alexandria"
theme = "material-lite"
TwitterUser = "_zchee_"
# FacebookUser = "YourFacebookUsername"
# GooglePlusUser = "YourGooglePlusUsername"
copyright = "&copy; a short copyright statement"
author = "zchee"
# background = "a relative or absolute URL to a background image"
# bgcolor = "a background color; will be ignored if you use background"
primary = "indigo"
accent = "pink"

[permalinks]
  post = "/:year/:month/:title/"

  [taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Library of Alexandria"
  author = "zchee <Koichi Shiraishi>"
